### ISSUE TITLE
Classification view: Rework header

### ISSUE THREAD

**Issue by lennart-huesing** [CombiRWTH/medical-staff-assessment#156]
Fix the date selection by using for example a calendar (date picker). And show the missing classifications in the calendar view.
Use german date format instead of american.
Put checkboxes somewhere else. Also use date format for "Tag der Entlassung" etc.

**Comment by lennart-huesing** [comment]
Also add the calculated category and minutes in the header.

**Comment by DasProffi** [comment]
Done in #160
