### ISSUE TITLE
API Defintion

### ISSUE THREAD

**Issue by DasProffi** [CombiRWTH/medical-staff-assessment#87]
# GET /stations/
```json
[
   {
      "id":"int",
      "name":"string",
      "patientCount":"int"  // Optional, Random Values possible
   }
]
```

# GET /stations/<stationId:int>
```json
[
   {
      "id":"int",
      "name":"string",
      "lastClassification":"Date",  // Optional, Random Values possible
      "currentBed": "string" // Optional, Random Values possible
   }
]
```

# GET /stations/<stationId:int>/<patienId:int>/<date:string>/classification/
```json
{
   "id":"int",
   "isDayOfAdmission":"bool",
   "isDayOfDischarge":"bool",
   "isInIsolation":"bool"
   "fields":[
      {
         "id":"int",
         "name":"string",
         "short":"string",
         "categories":[
            {
               "id":"int",
               "name":"string",
               "short":"string", // Empty string possible for now
               "severities":[
                  {
                     "severity":"int",
                     "options":[
                        {
                           "id":"int",
                           "index":"int",
                           "short":"string", // Empty string possible for now
                           "description":"string"
                        }
                     ]
                  }
               ]
            }
         ]
      }
   ]
}
```

# PUT /stations/<stationId:int>/<patienId:int>/<date:string>/questions/
```json
{
   "id":"int",
   "selcted":"bool"
}
```

# GET /stations/<stationId:int>/<patienId:int>/<date:string>/results/
```json
{
   "category1":"string",
   "category2":"string",
   "minutes":"int",
}
```

**Comment by lennart-huesing** [comment]
3,4,5 are handled by https://github.com/CombiRWTH/medical-staff-assessment/pull/72.

But the routes are a bit different (in respective order of course):
GET: questions/<int:station_id>/<int:patient_id>/<str:date>/
PUT: questions/<int:station_id>/<int:patient_id>/<str:date>/
GET: calculate/<int:station_id>/<int:patient_id>/<str:date>/

Some more information:
The results will also be in GET: questions/<int:station_id>/<int:patient_id>/<str:date>/. Calculate indicates a submission and triggers the calculation.

**Comment by benCoder01** [comment]
GET /stations/stationId:int will be handled via #81 (not finished yet)

**Comment by benCoder01** [comment]
When #90  and #72 are merged, all endpoints should be available. @aalhousseini therefore i will unassign you for that issue, as it is in the review phase.

**Comment by benCoder01** [comment]
All ednpoints should be implemented now, see here for more information: [https://github.com/CombiRWTH/medical-staff-assessment/wiki/REST-API]( https://github.com/CombiRWTH/medical-staff-assessment/wiki/REST-API) The json keys for `/api/questions/<int:station_id>/<int:patient_id>/<str:date>/` should be different than in the wiki, but the content should be like expected. (had not time to adapt it)
